---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: {{ item.taskrun_with_flavor_name }}-
spec:
  taskRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-tasks
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: {{ task_name }}
    - name: version
      value: {{ catalog_version }}
  params:
    - name: vmName
      value: vm-example
    - name: secretName
      value: {{ item.secret_name }}
    - name: command
      value:
        - systemctl
    - name: args
      value:
        - 'start'
        - 'postgresql.service'
