---
kind: Secret
apiVersion: v1
metadata:
  name: {{ item.secret_with_flavor_name }}
stringData:
  user: root
  disable-strict-host-key-checking: "true"
  ssh-privatekey: |-
    <private key should be here>

type: {{ item.secret_type }}
