---
kind: Secret
apiVersion: v1
metadata:
  name: ssh-secret
stringData:
  user: root
  disable-strict-host-key-checking: "true"
  ssh-privatekey: |
    <private key should be here>

type: kubernetes.io/ssh-auth
