version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    ignore:
      # Ginkgo, gomega update needs a change in automation/build-test.sh.
      - dependency-name: "github.com/onsi/ginkgo/v2"
      - dependency-name: "github.com/onsi/gomega"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 3
    labels:
      - "release-note-none"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  
    open-pull-requests-limit: 3
    labels:
      - "release-note-none"
