---
- connection: local
  hosts: 127.0.0.1
  gather_facts: no
  vars_files:
    - ../../configs/disk-uploader.yaml
    - ../../scripts/ansible/enums.yaml
    - ../../scripts/ansible/common.yaml
    - ../../scripts/ansible/branding.yaml
    - ../../scripts/ansible/variables.yaml
  tasks:
    - name: Init
      include_tasks: "{{ repo_dir }}/scripts/ansible/init-task-generation.yaml"
    - name: "Generate {{ task_name }} task"
      template:
        src: "{{ manifest_templates_dir }}/{{ task_name }}.yaml"
        dest: "{{ manifests_output_dir }}/{{ task_name }}.yaml"
        mode: "{{ default_file_mode }}"
    - name: Prepare examples dist directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ examples_output_dir }}"
        - "{{ examples_taskruns_output_dir }}"
    - name: Prepare readme dist directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ readme_output_dir_tmp }}"
    - name: Generate example task runs
      template:
        src: "{{ examples_templates_dir }}/{{ task_name }}-taskrun.yaml"
        dest: "{{ examples_taskruns_output_dir }}/{{ item.taskrun_with_flavor_name }}.yaml"
        mode: "{{ default_file_mode }}"
      with_items:
        - { taskrun_with_flavor_name: "{{ task_name }}-taskrun-resolver"}
    - name: Generate example secret of the task
      template:
        src: "{{ examples_templates_dir }}/{{ secret_task_name }}.yaml"
        dest: "{{ examples_taskruns_output_dir }}/{{ item.secret_task_with_flavor_name }}.yaml"
        mode: "{{ default_file_mode }}"
      with_items:
        - { secret_task_with_flavor_name: "{{ secret_task_name }}"}
    - name: Generate README
      template:
        src: "{{ readmes_templates_dir }}/README.md"
        dest: "{{ readme_output_dir }}/README.md"
        mode: "{{ default_file_mode }}"
      vars:
        task_path: "{{ manifests_output_dir }}/{{ task_name }}.yaml"
        task_yaml: "{{ lookup('file', task_path) | from_yaml }}"
        task_run_resolver_path: "{{ examples_taskruns_output_dir }}/{{ task_name }}-taskrun-resolver.yaml"
        task_run_resolver_yaml: "{{ lookup('file', task_run_resolver_path) | from_yaml }}"
        secret_task_path: "{{ examples_taskruns_output_dir }}/{{ secret_task_name }}.yaml"
        secret_task_yaml: "{{ lookup('file', secret_task_path) | from_yaml }}"
    - name: "Delete readme tmp directory"
      file:
        path: "{{ readme_output_dir_tmp }}"
        state: absent
