apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: {{ item.taskrun_with_flavor_name }}-
spec:
  taskRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-tasks
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: {{ task_name }}
    - name: version
      value: {{ catalog_version }}
  params:
  - name: EXPORT_SOURCE_KIND
    value: vm
  - name: EXPORT_SOURCE_NAME
    value: example-vm
  - name: VOLUME_NAME
    value: example-dv
  - name: IMAGE_DESTINATION
    value: quay.io/kubevirt/example-vm-exported:latest
  - name: SECRET_NAME
    value: disk-uploader-credentials
