apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  generateName: example-dv-
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
    volumeMode: Filesystem
  source:
    blank: {}