---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: generate-ssh-keys-advanced-taskrun
spec:
  serviceAccountName: generate-ssh-keys-task
  taskRef:
    kind: Task
    name: generate-ssh-keys
  params:
    - name: publicKeySecretName
      value: my-client-public-secret
    - name: privateKeySecretName
      value: my-client-private-secret
    - name: privateKeyConnectionOptions
      value:
        - 'user:root'
        - 'disable-strict-host-key-checking:true'
        - 'additional-ssh-options:-p 8022'
    - name: additionalSSHKeygenOptions
      value: '-t rsa-sha2-512 -b 4096'
