apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: unit-tester
spec:
  params:
    - name: vmName
      default: fedora-unit-tester
      type: string
    - name: privateKeySecretName
      default: unit-tester-client-private-key
      type: string
    - name: publicKeySecretName
      default: unit-tester-client-public-key
      type: string
  tasks:
    - name: generate-ssh-keys
      params:
        - name: publicKeySecretName
          value: $(params.publicKeySecretName)
        - name: privateKeySecretName
          value: $(params.privateKeySecretName)
        - name: privateKeyConnectionOptions
          value:
            - 'user:fedora'
            - 'disable-strict-host-key-checking:true'
      taskRef:
        kind: Task
        name: generate-ssh-keys
    - name: create-vm-from-manifest
      params:
        - name: manifest
          value: |
            apiVersion: kubevirt.io/v1
            kind: VirtualMachine
            metadata:
              name: $(params.vmName)
            spec:
              runStrategy: Halted
              template:
                metadata:
                  labels:
                    kubevirt.io/domain: $(params.vmName)
                spec:
                  accessCredentials:
                    - sshPublicKey:
                        source:
                          secret:
                            secretName: $(params.publicKeySecretName)
                        propagationMethod:
                          configDrive: {}
                  hostname: $(params.vmName)
                  domain:
                    cpu:
                      cores: 1
                      sockets: 1
                      threads: 1
                    devices:
                      disks:
                        - name: containerdisk
                          disk:
                            bus: virtio
                        - disk:
                            bus: virtio
                          name: cloudinitdisk
                      interfaces:
                        - bridge: {}
                          name: default
                          model: virtio
                      networkInterfaceMultiqueue: true
                      rng: {}
                    resources:
                      requests:
                        memory: 1Gi
                  networks:
                    - name: default
                      pod: {}
                  terminationGracePeriodSeconds: 0
                  volumes:
                    - name: containerdisk
                      containerDisk:
                        image: 'kubevirt/fedora-cloud-container-disk-demo:latest'
                    - name: cloudinitdisk
                      cloudInitConfigDrive:
                        userData: |
                          #cloud-config
      runAfter:
        - generate-ssh-keys
      taskRef:
        kind: Task
        name: create-vm-from-manifest
    - name: execute-in-vm
      params:
        - name: vmName
          value: "$(params.vmName)"
        - name: secretName
          value: "$(params.privateKeySecretName)"
        - name: script
          value: |
            #!/usr/bin/env bash
            set -ex

            sudo yum -y install git make go
            go get github.com/jstemmer/go-junit-report
            export PATH="$PATH:~/go/bin"
            git clone https://github.com/kubevirt/kubevirt-tekton-tasks.git
            cd kubevirt-tekton-tasks

            make test-with-reports
      runAfter:
        - create-vm-from-manifest
      taskRef:
        kind: Task
        name: execute-in-vm
  finally:
    - name: cleanup-vm
      params:
        - name: vmName
          value: "$(params.vmName)"
        - name: secretName
          value: "$(params.privateKeySecretName)"
        - name: delete
          value: "true"
        - name: timeout
          value: "5m"
        - name: script
          value: |
            #!/usr/bin/env bash
            RESULT_FILES="$(find . -name 'junit*.xml')"

            if [ -z  "${RESULT_FILES}" ]; then
              echo failure
            else
              echo success
              cat ${RESULT_FILES}
            fi
      taskRef:
        kind: Task
        name: cleanup-vm
