---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-vm-from-template-taskrun
spec:
  serviceAccountName: create-vm-from-template-task
  taskRef:
    kind: Task
    name: create-vm-from-template
  params:
  - name: templateName
    value: vm-template-example
  - name: templateParams
    value:
      - 'NAME:example-vm'
  - name: ownDataVolumes
    value:
      - example-dv
