---
- connection: local
  hosts: 127.0.0.1
  gather_facts: no
  vars_files:
    - ../../configs/cleanup-vm.yaml
    - ../../scripts/ansible/enums.yaml
    - ../../scripts/ansible/common.yaml
    - ../../scripts/ansible/branding.yaml
  vars:
    execute_in_vm_manifest_templates_dir: ../execute-in-vm/manifests
    execute_in_vm_examples_templates_dir: ../execute-in-vm/examples
    execute_in_vm_readmes_templates_dir: ../execute-in-vm/readmes
    examples_secrets_output_dir: "{{ examples_output_dir }}/secrets"
    ssh_secret_name: "ssh-secret"
  tasks:
    - name: Init
      include_tasks: "{{ repo_dir }}/scripts/ansible/init-task-generation.yaml"
    - name: "Generate {{ task_name }} task"
      template:
        src: "{{ execute_in_vm_manifest_templates_dir }}/{{ task_category }}.yaml"
        dest: "{{ manifests_output_dir }}/{{ task_name }}.yaml"
        mode: "{{ default_file_mode }}"
      vars:
        is_cleanup: true
    - name: Prepare examples dist directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ examples_output_dir }}"
        - "{{ examples_secrets_output_dir }}"
        - "{{ examples_taskruns_output_dir }}"
    - name: Prepare readme dist directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ readme_output_dir_tmp }}"
    - name: Generate roles
      include_tasks: "{{ repo_dir }}/scripts/ansible/generate-roles.yaml"
      with_items:
        - { role_type: ClusterRole, prefix: zz- }
      vars:
        role_output_dir: "{{ readme_output_dir_tmp }}"
    - name: Generate example secrets
      template:
        src: "{{ execute_in_vm_examples_templates_dir }}/{{ ssh_secret_name }}.yaml"
        dest: "{{ examples_secrets_output_dir }}/{{ item.secret_with_flavor_name }}.yaml"
        mode: "{{ default_file_mode }}"
      with_items:
        - { secret_type: kubernetes.io/ssh-auth, secret_with_flavor_name: "{{ ssh_secret_name }}" }
    - name: Generate example task runs
      template:
        src: "{{ examples_templates_dir }}/{{ task_name }}-taskrun.yaml"
        dest: "{{ examples_taskruns_output_dir }}/{{ item.taskrun_with_flavor_name }}.yaml"
        mode: "{{ default_file_mode }}"
      with_items:
        - { taskrun_with_flavor_name: "{{ task_name }}-taskrun-resolver", secret_name: "{{ ssh_secret_name }}" }
    - name: Generate README
      template:
        src: "{{ execute_in_vm_readmes_templates_dir }}/README.md"
        dest: "{{ readme_output_dir }}/README.md"
        mode: "{{ default_file_mode }}"
      vars:
        is_cleanup: true
        task_path: "{{ manifests_output_dir }}/{{ task_name }}.yaml"
        task_yaml: "{{ lookup('file', task_path) | from_yaml }}"
        rbac_path: "{{ readme_output_dir_tmp }}/zz-{{ task_name }}-rbac.yaml"
        rbac_yaml: "{{ lookup('file', rbac_path) | from_yaml_all }}"
        advanced_task_run_path: "{{ examples_taskruns_output_dir }}/{{ task_name }}-with-ssh-taskrun.yaml"
        advanced_task_run_yaml: "{{ lookup('file', advanced_task_run_path) | from_yaml }}"
        simple_task_run_path: "{{ examples_taskruns_output_dir }}/{{ task_name }}-simple-taskrun.yaml"
        simple_task_run_yaml: "{{ lookup('file', simple_task_run_path) | from_yaml }}"
        ssh_secret_path: "{{ examples_secrets_output_dir }}/{{ ssh_secret_name }}.yaml"
        ssh_secret_yaml: "{{ lookup('file', ssh_secret_path) | from_yaml }}"
        ssh_task_run_resolver_path: "{{ examples_taskruns_output_dir }}/{{ task_name }}-taskrun-resolver.yaml"
        ssh_task_run_resolver_yaml: "{{ lookup('file', ssh_task_run_resolver_path) | from_yaml }}"
    - name: "Delete readme tmp directory"
      file:
        path: "{{ readme_output_dir_tmp }}"
        state: absent

