---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: {{ item.taskrun_with_flavor_name }}-
spec:
  taskRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-tasks
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: {{ task_name }}
    - name: version
      value: {{ version }}
  params:
  - name: templateName
    value: vm-template-example
  - name: templateParams
    value:
      - 'NAME:example-vm'
  - name: ownDataVolumes
    value:
      - example-dv
