---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: disk-uploader-pipeline-run
spec:
  pipelineRef:
    name: disk-uploader-pipeline
  params:
  - name: EXPORT_SOURCE_KIND
    value: vm
  - name: EXPORT_SOURCE_NAME
    value: example-vm
  - name: VOLUME_NAME
    value: example-dv
  - name: IMAGE_DESTINATION
    value: quay.io/kubevirt/example-vm-exported:latest
  taskRunTemplate:
    serviceAccountName: disk-uploader
