---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: disk-uploader
rules:
- apiGroups: ["export.kubevirt.io"]
  resources: ["virtualmachineexports"]
  verbs: ["get", "create"]
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get"]
