---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: {{ item.taskrun_with_flavor_name }}-
spec:
  taskRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-tasks
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: {{ task_name }}
    - name: version
      value: {{ version }}
  params:
    - name: vmiName
      value: example-vm
    - name: successCondition
      value: "status.phase == Succeeded"
    - name: failureCondition
      value: "status.phase in (Failed, Unknown)"
