---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: {{ item.taskrun_with_flavor_name }}
spec:
  serviceAccountName: {{ sa_name }}
  taskRef:
    kind: Task
    name: {{ task_name }}
  params:
    - name: vmiName
      value: example-vm
    - name: successCondition
      value: "status.phase == Succeeded"
    - name: failureCondition
      value: "status.phase in (Failed, Unknown)"
