---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows11-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: ${WIN_IMAGE_DOWNLOAD_URL}
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: {{ pipelines_catalog }}
      - name: type
        value: {{ catalog_type }}
      - name: kind
        value: task
      - name: name
        value: {{ item.pipeline_name }}
      - name: version
        value: {{ version }}
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows2k22-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: ${WIN_IMAGE_DOWNLOAD_URL}
    - name: preferenceName
      value: windows.2k22
    - name: autounattendConfigMapName
      value: windows2k22-autounattend
    - name: baseDvName
      value: win2k22
    - name: isoDVName
      value: win2k22
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: {{ pipelines_catalog }}
      - name: type
        value: {{ catalog_type }}
      - name: kind
        value: task
      - name: name
        value: {{ item.pipeline_name }}
      - name: version
        value: {{ version }}
  timeout: 1h0m0s
