task_param_types:
  boolean: boolean
  namespace: namespace
  duration: duration
  script: script
  resource_yaml: resource-yaml
  v1_version: v1
  secret_kind: Secret
  pvc_kind: PersistentVolumeClaim
  vm_version: kubevirt.io/v1
  vm_kind: VirtualMachine
  cdi_beta_api_version: cdi.kubevirt.io/v1beta1
  datavolume_kind: DataVolume
  private_key_options_array: private-key-options-array
  execute_in_vm_secret: execute-in-vm-secret
  memory: memory
  number: number
