---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: copy-template-taskrun
spec:
  serviceAccountName: copy-template-task
  taskRef:
    kind: Task
    name: copy-template
  params:
  - name: sourceTemplateName
    value: source-vm-template-example
  - name: targetTemplateName
    value: target-vm-template-example
